// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net.proto

package common.network;

public final class NetworkProto {
  private NetworkProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class NetworkEntity extends
      com.google.protobuf.GeneratedMessage {
    // Use NetworkEntity.newBuilder() to construct.
    private NetworkEntity() {
      initFields();
    }
    private NetworkEntity(boolean noInit) {}
    
    private static final NetworkEntity defaultInstance;
    public static NetworkEntity getDefaultInstance() {
      return defaultInstance;
    }
    
    public NetworkEntity getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return common.network.NetworkProto.internal_static_common_network_NetworkEntity_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return common.network.NetworkProto.internal_static_common_network_NetworkEntity_fieldAccessorTable;
    }
    
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional float x = 2;
    public static final int X_FIELD_NUMBER = 2;
    private boolean hasX;
    private float x_ = 0F;
    public boolean hasX() { return hasX; }
    public float getX() { return x_; }
    
    // optional float y = 3;
    public static final int Y_FIELD_NUMBER = 3;
    private boolean hasY;
    private float y_ = 0F;
    public boolean hasY() { return hasY; }
    public float getY() { return y_; }
    
    // optional float xvel = 4;
    public static final int XVEL_FIELD_NUMBER = 4;
    private boolean hasXvel;
    private float xvel_ = 0F;
    public boolean hasXvel() { return hasXvel; }
    public float getXvel() { return xvel_; }
    
    // optional float yvel = 5;
    public static final int YVEL_FIELD_NUMBER = 5;
    private boolean hasYvel;
    private float yvel_ = 0F;
    public boolean hasYvel() { return hasYvel; }
    public float getYvel() { return yvel_; }
    
    // optional float r = 6;
    public static final int R_FIELD_NUMBER = 6;
    private boolean hasR;
    private float r_ = 0F;
    public boolean hasR() { return hasR; }
    public float getR() { return r_; }
    
    // optional float rvel = 7;
    public static final int RVEL_FIELD_NUMBER = 7;
    private boolean hasRvel;
    private float rvel_ = 0F;
    public boolean hasRvel() { return hasRvel; }
    public float getRvel() { return rvel_; }
    
    // optional int32 model = 8;
    public static final int MODEL_FIELD_NUMBER = 8;
    private boolean hasModel;
    private int model_ = 0;
    public boolean hasModel() { return hasModel; }
    public int getModel() { return model_; }
    
    // optional int32 type = 9;
    public static final int TYPE_FIELD_NUMBER = 9;
    private boolean hasType;
    private int type_ = 0;
    public boolean hasType() { return hasType; }
    public int getType() { return type_; }
    
    // optional float aim = 10;
    public static final int AIM_FIELD_NUMBER = 10;
    private boolean hasAim;
    private float aim_ = 0F;
    public boolean hasAim() { return hasAim; }
    public float getAim() { return aim_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasX()) {
        output.writeFloat(2, getX());
      }
      if (hasY()) {
        output.writeFloat(3, getY());
      }
      if (hasXvel()) {
        output.writeFloat(4, getXvel());
      }
      if (hasYvel()) {
        output.writeFloat(5, getYvel());
      }
      if (hasR()) {
        output.writeFloat(6, getR());
      }
      if (hasRvel()) {
        output.writeFloat(7, getRvel());
      }
      if (hasModel()) {
        output.writeInt32(8, getModel());
      }
      if (hasType()) {
        output.writeInt32(9, getType());
      }
      if (hasAim()) {
        output.writeFloat(10, getAim());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasX()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, getX());
      }
      if (hasY()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, getY());
      }
      if (hasXvel()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, getXvel());
      }
      if (hasYvel()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, getYvel());
      }
      if (hasR()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, getR());
      }
      if (hasRvel()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, getRvel());
      }
      if (hasModel()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, getModel());
      }
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, getType());
      }
      if (hasAim()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, getAim());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static common.network.NetworkProto.NetworkEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static common.network.NetworkProto.NetworkEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static common.network.NetworkProto.NetworkEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static common.network.NetworkProto.NetworkEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static common.network.NetworkProto.NetworkEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static common.network.NetworkProto.NetworkEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static common.network.NetworkProto.NetworkEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static common.network.NetworkProto.NetworkEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static common.network.NetworkProto.NetworkEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static common.network.NetworkProto.NetworkEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(common.network.NetworkProto.NetworkEntity prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private common.network.NetworkProto.NetworkEntity result;
      
      // Construct using common.network.NetworkProto.NetworkEntity.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new common.network.NetworkProto.NetworkEntity();
        return builder;
      }
      
      protected common.network.NetworkProto.NetworkEntity internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new common.network.NetworkProto.NetworkEntity();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return common.network.NetworkProto.NetworkEntity.getDescriptor();
      }
      
      public common.network.NetworkProto.NetworkEntity getDefaultInstanceForType() {
        return common.network.NetworkProto.NetworkEntity.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public common.network.NetworkProto.NetworkEntity build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private common.network.NetworkProto.NetworkEntity buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public common.network.NetworkProto.NetworkEntity buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        common.network.NetworkProto.NetworkEntity returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof common.network.NetworkProto.NetworkEntity) {
          return mergeFrom((common.network.NetworkProto.NetworkEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(common.network.NetworkProto.NetworkEntity other) {
        if (other == common.network.NetworkProto.NetworkEntity.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasXvel()) {
          setXvel(other.getXvel());
        }
        if (other.hasYvel()) {
          setYvel(other.getYvel());
        }
        if (other.hasR()) {
          setR(other.getR());
        }
        if (other.hasRvel()) {
          setRvel(other.getRvel());
        }
        if (other.hasModel()) {
          setModel(other.getModel());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasAim()) {
          setAim(other.getAim());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 21: {
              setX(input.readFloat());
              break;
            }
            case 29: {
              setY(input.readFloat());
              break;
            }
            case 37: {
              setXvel(input.readFloat());
              break;
            }
            case 45: {
              setYvel(input.readFloat());
              break;
            }
            case 53: {
              setR(input.readFloat());
              break;
            }
            case 61: {
              setRvel(input.readFloat());
              break;
            }
            case 64: {
              setModel(input.readInt32());
              break;
            }
            case 72: {
              setType(input.readInt32());
              break;
            }
            case 85: {
              setAim(input.readFloat());
              break;
            }
          }
        }
      }
      
      
      // optional int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional float x = 2;
      public boolean hasX() {
        return result.hasX();
      }
      public float getX() {
        return result.getX();
      }
      public Builder setX(float value) {
        result.hasX = true;
        result.x_ = value;
        return this;
      }
      public Builder clearX() {
        result.hasX = false;
        result.x_ = 0F;
        return this;
      }
      
      // optional float y = 3;
      public boolean hasY() {
        return result.hasY();
      }
      public float getY() {
        return result.getY();
      }
      public Builder setY(float value) {
        result.hasY = true;
        result.y_ = value;
        return this;
      }
      public Builder clearY() {
        result.hasY = false;
        result.y_ = 0F;
        return this;
      }
      
      // optional float xvel = 4;
      public boolean hasXvel() {
        return result.hasXvel();
      }
      public float getXvel() {
        return result.getXvel();
      }
      public Builder setXvel(float value) {
        result.hasXvel = true;
        result.xvel_ = value;
        return this;
      }
      public Builder clearXvel() {
        result.hasXvel = false;
        result.xvel_ = 0F;
        return this;
      }
      
      // optional float yvel = 5;
      public boolean hasYvel() {
        return result.hasYvel();
      }
      public float getYvel() {
        return result.getYvel();
      }
      public Builder setYvel(float value) {
        result.hasYvel = true;
        result.yvel_ = value;
        return this;
      }
      public Builder clearYvel() {
        result.hasYvel = false;
        result.yvel_ = 0F;
        return this;
      }
      
      // optional float r = 6;
      public boolean hasR() {
        return result.hasR();
      }
      public float getR() {
        return result.getR();
      }
      public Builder setR(float value) {
        result.hasR = true;
        result.r_ = value;
        return this;
      }
      public Builder clearR() {
        result.hasR = false;
        result.r_ = 0F;
        return this;
      }
      
      // optional float rvel = 7;
      public boolean hasRvel() {
        return result.hasRvel();
      }
      public float getRvel() {
        return result.getRvel();
      }
      public Builder setRvel(float value) {
        result.hasRvel = true;
        result.rvel_ = value;
        return this;
      }
      public Builder clearRvel() {
        result.hasRvel = false;
        result.rvel_ = 0F;
        return this;
      }
      
      // optional int32 model = 8;
      public boolean hasModel() {
        return result.hasModel();
      }
      public int getModel() {
        return result.getModel();
      }
      public Builder setModel(int value) {
        result.hasModel = true;
        result.model_ = value;
        return this;
      }
      public Builder clearModel() {
        result.hasModel = false;
        result.model_ = 0;
        return this;
      }
      
      // optional int32 type = 9;
      public boolean hasType() {
        return result.hasType();
      }
      public int getType() {
        return result.getType();
      }
      public Builder setType(int value) {
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = 0;
        return this;
      }
      
      // optional float aim = 10;
      public boolean hasAim() {
        return result.hasAim();
      }
      public float getAim() {
        return result.getAim();
      }
      public Builder setAim(float value) {
        result.hasAim = true;
        result.aim_ = value;
        return this;
      }
      public Builder clearAim() {
        result.hasAim = false;
        result.aim_ = 0F;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:common.network.NetworkEntity)
    }
    
    static {
      defaultInstance = new NetworkEntity(true);
      common.network.NetworkProto.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:common.network.NetworkEntity)
  }
  
  public static final class NetworkChunk extends
      com.google.protobuf.GeneratedMessage {
    // Use NetworkChunk.newBuilder() to construct.
    private NetworkChunk() {
      initFields();
    }
    private NetworkChunk(boolean noInit) {}
    
    private static final NetworkChunk defaultInstance;
    public static NetworkChunk getDefaultInstance() {
      return defaultInstance;
    }
    
    public NetworkChunk getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return common.network.NetworkProto.internal_static_common_network_NetworkChunk_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return common.network.NetworkProto.internal_static_common_network_NetworkChunk_fieldAccessorTable;
    }
    
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional float x = 2;
    public static final int X_FIELD_NUMBER = 2;
    private boolean hasX;
    private float x_ = 0F;
    public boolean hasX() { return hasX; }
    public float getX() { return x_; }
    
    // optional float y = 3;
    public static final int Y_FIELD_NUMBER = 3;
    private boolean hasY;
    private float y_ = 0F;
    public boolean hasY() { return hasY; }
    public float getY() { return y_; }
    
    // optional bytes data = 4;
    public static final int DATA_FIELD_NUMBER = 4;
    private boolean hasData;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasData() { return hasData; }
    public com.google.protobuf.ByteString getData() { return data_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasX()) {
        output.writeFloat(2, getX());
      }
      if (hasY()) {
        output.writeFloat(3, getY());
      }
      if (hasData()) {
        output.writeBytes(4, getData());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasX()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, getX());
      }
      if (hasY()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, getY());
      }
      if (hasData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static common.network.NetworkProto.NetworkChunk parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static common.network.NetworkProto.NetworkChunk parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static common.network.NetworkProto.NetworkChunk parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static common.network.NetworkProto.NetworkChunk parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static common.network.NetworkProto.NetworkChunk parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static common.network.NetworkProto.NetworkChunk parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static common.network.NetworkProto.NetworkChunk parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static common.network.NetworkProto.NetworkChunk parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static common.network.NetworkProto.NetworkChunk parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static common.network.NetworkProto.NetworkChunk parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(common.network.NetworkProto.NetworkChunk prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private common.network.NetworkProto.NetworkChunk result;
      
      // Construct using common.network.NetworkProto.NetworkChunk.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new common.network.NetworkProto.NetworkChunk();
        return builder;
      }
      
      protected common.network.NetworkProto.NetworkChunk internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new common.network.NetworkProto.NetworkChunk();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return common.network.NetworkProto.NetworkChunk.getDescriptor();
      }
      
      public common.network.NetworkProto.NetworkChunk getDefaultInstanceForType() {
        return common.network.NetworkProto.NetworkChunk.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public common.network.NetworkProto.NetworkChunk build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private common.network.NetworkProto.NetworkChunk buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public common.network.NetworkProto.NetworkChunk buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        common.network.NetworkProto.NetworkChunk returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof common.network.NetworkProto.NetworkChunk) {
          return mergeFrom((common.network.NetworkProto.NetworkChunk)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(common.network.NetworkProto.NetworkChunk other) {
        if (other == common.network.NetworkProto.NetworkChunk.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 21: {
              setX(input.readFloat());
              break;
            }
            case 29: {
              setY(input.readFloat());
              break;
            }
            case 34: {
              setData(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // optional int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional float x = 2;
      public boolean hasX() {
        return result.hasX();
      }
      public float getX() {
        return result.getX();
      }
      public Builder setX(float value) {
        result.hasX = true;
        result.x_ = value;
        return this;
      }
      public Builder clearX() {
        result.hasX = false;
        result.x_ = 0F;
        return this;
      }
      
      // optional float y = 3;
      public boolean hasY() {
        return result.hasY();
      }
      public float getY() {
        return result.getY();
      }
      public Builder setY(float value) {
        result.hasY = true;
        result.y_ = value;
        return this;
      }
      public Builder clearY() {
        result.hasY = false;
        result.y_ = 0F;
        return this;
      }
      
      // optional bytes data = 4;
      public boolean hasData() {
        return result.hasData();
      }
      public com.google.protobuf.ByteString getData() {
        return result.getData();
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasData = true;
        result.data_ = value;
        return this;
      }
      public Builder clearData() {
        result.hasData = false;
        result.data_ = getDefaultInstance().getData();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:common.network.NetworkChunk)
    }
    
    static {
      defaultInstance = new NetworkChunk(true);
      common.network.NetworkProto.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:common.network.NetworkChunk)
  }
  
  public static final class NetworkKeyEvent extends
      com.google.protobuf.GeneratedMessage {
    // Use NetworkKeyEvent.newBuilder() to construct.
    private NetworkKeyEvent() {
      initFields();
    }
    private NetworkKeyEvent(boolean noInit) {}
    
    private static final NetworkKeyEvent defaultInstance;
    public static NetworkKeyEvent getDefaultInstance() {
      return defaultInstance;
    }
    
    public NetworkKeyEvent getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return common.network.NetworkProto.internal_static_common_network_NetworkKeyEvent_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return common.network.NetworkProto.internal_static_common_network_NetworkKeyEvent_fieldAccessorTable;
    }
    
    // optional int32 key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private boolean hasKey;
    private int key_ = 0;
    public boolean hasKey() { return hasKey; }
    public int getKey() { return key_; }
    
    // optional bool down = 2;
    public static final int DOWN_FIELD_NUMBER = 2;
    private boolean hasDown;
    private boolean down_ = false;
    public boolean hasDown() { return hasDown; }
    public boolean getDown() { return down_; }
    
    // optional int64 time = 3;
    public static final int TIME_FIELD_NUMBER = 3;
    private boolean hasTime;
    private long time_ = 0L;
    public boolean hasTime() { return hasTime; }
    public long getTime() { return time_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasKey()) {
        output.writeInt32(1, getKey());
      }
      if (hasDown()) {
        output.writeBool(2, getDown());
      }
      if (hasTime()) {
        output.writeInt64(3, getTime());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getKey());
      }
      if (hasDown()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, getDown());
      }
      if (hasTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, getTime());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static common.network.NetworkProto.NetworkKeyEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static common.network.NetworkProto.NetworkKeyEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static common.network.NetworkProto.NetworkKeyEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static common.network.NetworkProto.NetworkKeyEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static common.network.NetworkProto.NetworkKeyEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static common.network.NetworkProto.NetworkKeyEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static common.network.NetworkProto.NetworkKeyEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static common.network.NetworkProto.NetworkKeyEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static common.network.NetworkProto.NetworkKeyEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static common.network.NetworkProto.NetworkKeyEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(common.network.NetworkProto.NetworkKeyEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private common.network.NetworkProto.NetworkKeyEvent result;
      
      // Construct using common.network.NetworkProto.NetworkKeyEvent.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new common.network.NetworkProto.NetworkKeyEvent();
        return builder;
      }
      
      protected common.network.NetworkProto.NetworkKeyEvent internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new common.network.NetworkProto.NetworkKeyEvent();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return common.network.NetworkProto.NetworkKeyEvent.getDescriptor();
      }
      
      public common.network.NetworkProto.NetworkKeyEvent getDefaultInstanceForType() {
        return common.network.NetworkProto.NetworkKeyEvent.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public common.network.NetworkProto.NetworkKeyEvent build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private common.network.NetworkProto.NetworkKeyEvent buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public common.network.NetworkProto.NetworkKeyEvent buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        common.network.NetworkProto.NetworkKeyEvent returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof common.network.NetworkProto.NetworkKeyEvent) {
          return mergeFrom((common.network.NetworkProto.NetworkKeyEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(common.network.NetworkProto.NetworkKeyEvent other) {
        if (other == common.network.NetworkProto.NetworkKeyEvent.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasDown()) {
          setDown(other.getDown());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setKey(input.readInt32());
              break;
            }
            case 16: {
              setDown(input.readBool());
              break;
            }
            case 24: {
              setTime(input.readInt64());
              break;
            }
          }
        }
      }
      
      
      // optional int32 key = 1;
      public boolean hasKey() {
        return result.hasKey();
      }
      public int getKey() {
        return result.getKey();
      }
      public Builder setKey(int value) {
        result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = 0;
        return this;
      }
      
      // optional bool down = 2;
      public boolean hasDown() {
        return result.hasDown();
      }
      public boolean getDown() {
        return result.getDown();
      }
      public Builder setDown(boolean value) {
        result.hasDown = true;
        result.down_ = value;
        return this;
      }
      public Builder clearDown() {
        result.hasDown = false;
        result.down_ = false;
        return this;
      }
      
      // optional int64 time = 3;
      public boolean hasTime() {
        return result.hasTime();
      }
      public long getTime() {
        return result.getTime();
      }
      public Builder setTime(long value) {
        result.hasTime = true;
        result.time_ = value;
        return this;
      }
      public Builder clearTime() {
        result.hasTime = false;
        result.time_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:common.network.NetworkKeyEvent)
    }
    
    static {
      defaultInstance = new NetworkKeyEvent(true);
      common.network.NetworkProto.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:common.network.NetworkKeyEvent)
  }
  
  public static final class NetworkMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use NetworkMessage.newBuilder() to construct.
    private NetworkMessage() {
      initFields();
    }
    private NetworkMessage(boolean noInit) {}
    
    private static final NetworkMessage defaultInstance;
    public static NetworkMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public NetworkMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return common.network.NetworkProto.internal_static_common_network_NetworkMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return common.network.NetworkProto.internal_static_common_network_NetworkMessage_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      CLIENT_READY(0, 0),
      GRANT_CONTROL(1, 1),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 0: return CLIENT_READY;
          case 1: return GRANT_CONTROL;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return common.network.NetworkProto.NetworkMessage.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        CLIENT_READY, GRANT_CONTROL, 
      };
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        common.network.NetworkProto.getDescriptor();
      }
      
      // @@protoc_insertion_point(enum_scope:common.network.NetworkMessage.Type)
    }
    
    // optional .common.network.NetworkMessage.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private boolean hasType;
    private common.network.NetworkProto.NetworkMessage.Type type_;
    public boolean hasType() { return hasType; }
    public common.network.NetworkProto.NetworkMessage.Type getType() { return type_; }
    
    // optional int32 target = 2;
    public static final int TARGET_FIELD_NUMBER = 2;
    private boolean hasTarget;
    private int target_ = 0;
    public boolean hasTarget() { return hasTarget; }
    public int getTarget() { return target_; }
    
    private void initFields() {
      type_ = common.network.NetworkProto.NetworkMessage.Type.CLIENT_READY;
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasType()) {
        output.writeEnum(1, getType().getNumber());
      }
      if (hasTarget()) {
        output.writeInt32(2, getTarget());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getType().getNumber());
      }
      if (hasTarget()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getTarget());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static common.network.NetworkProto.NetworkMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static common.network.NetworkProto.NetworkMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static common.network.NetworkProto.NetworkMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static common.network.NetworkProto.NetworkMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static common.network.NetworkProto.NetworkMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static common.network.NetworkProto.NetworkMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static common.network.NetworkProto.NetworkMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static common.network.NetworkProto.NetworkMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static common.network.NetworkProto.NetworkMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static common.network.NetworkProto.NetworkMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(common.network.NetworkProto.NetworkMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private common.network.NetworkProto.NetworkMessage result;
      
      // Construct using common.network.NetworkProto.NetworkMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new common.network.NetworkProto.NetworkMessage();
        return builder;
      }
      
      protected common.network.NetworkProto.NetworkMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new common.network.NetworkProto.NetworkMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return common.network.NetworkProto.NetworkMessage.getDescriptor();
      }
      
      public common.network.NetworkProto.NetworkMessage getDefaultInstanceForType() {
        return common.network.NetworkProto.NetworkMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public common.network.NetworkProto.NetworkMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private common.network.NetworkProto.NetworkMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public common.network.NetworkProto.NetworkMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        common.network.NetworkProto.NetworkMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof common.network.NetworkProto.NetworkMessage) {
          return mergeFrom((common.network.NetworkProto.NetworkMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(common.network.NetworkProto.NetworkMessage other) {
        if (other == common.network.NetworkProto.NetworkMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasTarget()) {
          setTarget(other.getTarget());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              common.network.NetworkProto.NetworkMessage.Type value = common.network.NetworkProto.NetworkMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                setType(value);
              }
              break;
            }
            case 16: {
              setTarget(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional .common.network.NetworkMessage.Type type = 1;
      public boolean hasType() {
        return result.hasType();
      }
      public common.network.NetworkProto.NetworkMessage.Type getType() {
        return result.getType();
      }
      public Builder setType(common.network.NetworkProto.NetworkMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = common.network.NetworkProto.NetworkMessage.Type.CLIENT_READY;
        return this;
      }
      
      // optional int32 target = 2;
      public boolean hasTarget() {
        return result.hasTarget();
      }
      public int getTarget() {
        return result.getTarget();
      }
      public Builder setTarget(int value) {
        result.hasTarget = true;
        result.target_ = value;
        return this;
      }
      public Builder clearTarget() {
        result.hasTarget = false;
        result.target_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:common.network.NetworkMessage)
    }
    
    static {
      defaultInstance = new NetworkMessage(true);
      common.network.NetworkProto.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:common.network.NetworkMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_common_network_NetworkEntity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_network_NetworkEntity_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_common_network_NetworkChunk_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_network_NetworkChunk_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_common_network_NetworkKeyEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_network_NetworkKeyEvent_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_common_network_NetworkMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_network_NetworkMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tnet.proto\022\016common.network\"\220\001\n\rNetworkE" +
      "ntity\022\n\n\002id\030\001 \001(\005\022\t\n\001x\030\002 \001(\002\022\t\n\001y\030\003 \001(\002\022" +
      "\014\n\004xvel\030\004 \001(\002\022\014\n\004yvel\030\005 \001(\002\022\t\n\001r\030\006 \001(\002\022\014" +
      "\n\004rvel\030\007 \001(\002\022\r\n\005model\030\010 \001(\005\022\014\n\004type\030\t \001(" +
      "\005\022\013\n\003aim\030\n \001(\002\">\n\014NetworkChunk\022\n\n\002id\030\001 \001" +
      "(\005\022\t\n\001x\030\002 \001(\002\022\t\n\001y\030\003 \001(\002\022\014\n\004data\030\004 \001(\014\":" +
      "\n\017NetworkKeyEvent\022\013\n\003key\030\001 \001(\005\022\014\n\004down\030\002" +
      " \001(\010\022\014\n\004time\030\003 \001(\003\"\200\001\n\016NetworkMessage\0221\n" +
      "\004type\030\001 \001(\0162#.common.network.NetworkMess" +
      "age.Type\022\016\n\006target\030\002 \001(\005\"+\n\004Type\022\020\n\014CLIE",
      "NT_READY\020\000\022\021\n\rGRANT_CONTROL\020\001B\036\n\016common." +
      "networkB\014NetworkProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_common_network_NetworkEntity_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_common_network_NetworkEntity_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_common_network_NetworkEntity_descriptor,
              new java.lang.String[] { "Id", "X", "Y", "Xvel", "Yvel", "R", "Rvel", "Model", "Type", "Aim", },
              common.network.NetworkProto.NetworkEntity.class,
              common.network.NetworkProto.NetworkEntity.Builder.class);
          internal_static_common_network_NetworkChunk_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_common_network_NetworkChunk_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_common_network_NetworkChunk_descriptor,
              new java.lang.String[] { "Id", "X", "Y", "Data", },
              common.network.NetworkProto.NetworkChunk.class,
              common.network.NetworkProto.NetworkChunk.Builder.class);
          internal_static_common_network_NetworkKeyEvent_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_common_network_NetworkKeyEvent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_common_network_NetworkKeyEvent_descriptor,
              new java.lang.String[] { "Key", "Down", "Time", },
              common.network.NetworkProto.NetworkKeyEvent.class,
              common.network.NetworkProto.NetworkKeyEvent.Builder.class);
          internal_static_common_network_NetworkMessage_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_common_network_NetworkMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_common_network_NetworkMessage_descriptor,
              new java.lang.String[] { "Type", "Target", },
              common.network.NetworkProto.NetworkMessage.class,
              common.network.NetworkProto.NetworkMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
